[build]
  command = "npm run build" # the command you run to build this file
  functions = "/dist/built-lambda" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "/dist/public"

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/main"
  status = 200
  force = false
