scalar Date

enum ParticipantRole{
    Organiser
    VIP
    Participant
    Emcee
}

type Label{
    id: ID
    name: String
    createdAt: Date
}

type Picture{
    id: ID
    url: String
    alt: String
    caption: String
}

type Address{
    id: ID
    city: String
    country: String
    street: String
    houseNumber: Int
    addition: String
}

type Location{
    lat: Float
    lng: Float
}

type Person{
    id: ID
    firstName: String
    lastName: String
    callSign: String
    createdAt: Date
    updatedAt: Date
    picture: Picture
}

type Brand{
    id: ID
    name: String
    slug: String
    logo: String
    events: [Event]
    labels: [Label]
    createdAt: Date
    updatedAt: Date
}

type Event{
    id: ID
    slug: String
    name: String
    startsAt: Date
    endsAt: Date
    brand: Brand
    speakers: [Speaker]
    schedule: [Schedule]
    sponsors: [Sponsor]
    participants: [Participant]
    attendees: [Attendee]
    people: [Person]
    venue: Venue
    talks: [Talk]
    labels: [Label]
    createdAt: Date
    updatedAt: Date
}

type Organisation{
    id: ID
    slug: String
    name: String
    website: String
    sponsorships: [Sponsor]
}

type Sponsor{
    id: ID
    event: Event
    organisation: Organisation
    level: String
}

type Venue{
    id: ID
    slug: String
    name: String
    description: String
    organisation: [Organisation]
    pictures: [Picture]
    address: Address
    location: Location
}

type Participant{
    id: ID
    event: Event
    person: Person
    role: ParticipantRole
}

type Speaker{
    id: ID
    person: Person
    event: Event
    timeslot: Timeslot
    talk: Talk
}

type Talk{
    id: ID
    title: String
    description: String
    event: Event
    speaker: Speaker
}

type Timeslot{
    id: ID
    title: String
    description: String
    schedule: Schedule
    talk: Talk
    startsAt: Date
    endsAt: Date
    createdAt: Date
    updatedAt: Date
}

type Schedule{
    id: ID
    title: String
    event: Event
    timeslots: [Timeslot]
    createdAt: Date
    updatedAt: Date
}

type Ticket{
    id: ID
    token: String
}

type Attendee{
    id: ID
    person: Person
    ticket: Ticket
}

type Query{
    brand(
        id: ID
        slug: String
    ): Brand
    brands: [Brand]
    event(
        id: ID
        brandSlug: String
    ): Event
    events(
        brandSlug: String
    ): [Event]
    speaker(
        id: ID
    ): Speaker
    speakers(
        eventId: ID
    ): [Speaker]
    schedule(
        eventId: ID
    ): Schedule
    attendees(
        eventId: ID
    ): [Attendee]
    organisation(id: ID): Organisation
    organisations(slug: String): [Organisation]
    person: Person
    people: [Person]
}
